### ISSUE TITLE
Github action to build the repository (to update the documentation) cannot be manually triggered

### ISSUE THREAD

**Issue by ddelnano** [terra-farm/terra-farm.github.io#5]
I have written some updated documentation for the [terraform-provider-xenorchestra](https://github.com/terra-farm/terraform-provider-xenorchestra) project. Unfortunately when this repo was moved from Travis CI to GitHub actions, I lost the ability to trigger a build of the master branch which would update the xenorchestra documentation so the website has had stale documentation since I merged [this](https://github.com/terra-farm/terraform-provider-xenorchestra/pull/31) change.

It seems like this could be fixed with https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

**Comment by ddelnano** [comment]
@ringods were you able to see that the "Run workflow" button shows up in the Actions tab? If so can we expand my permissions so that I can do the same? Haven't tried this on a repo I have full control with so not sure how granular the actions permissions are.

**Comment by ringods** [comment]
@ddelnano We should get the providers under this organization published on the [Terraform Registry](https://registry.terraform.io) now that TF 0.13 is released. This removes the need for the manual provider installation towards the users of the providers.

If you need help or additional information to get your provider published, please open an issue in your own provider repository and will help out where I can.

To have some consistency amongst all providers, it is best to also have the docs published on the Registry too. The Terra-Farm website will become a placeholder regarding the project and pointers to all the providers, all pointing to the Registry for the docs. Not that I don't want to, but it's of no use to expand your permissions here as a result.

Here is an example of the docs for the Github provider:
https://registry.terraform.io/providers/hashicorp/github/latest/docs

**Comment by ddelnano** [comment]
I just [published](https://registry.terraform.io/providers/terra-farm/xenorchestra/latest?pollNotifications=true) the xenorchestra provider on terraform registry and thanks for getting the ball rolling on that!
